### PR TITLE
Added Python code for example in Karl's google doc

### PR DESCRIPTION
**Pull request by doutriaux1**
@taylor13 please review

### CODE REVIEW

**Comment by mauzey1** [comment]
There's is a duplicate of example 2 that is listed as example 3 in mydoc_cmor3_python.md.

**Comment by mauzey1** [comment]
Did you want to link the JSON files from the /mydoc/examples/ directory rather than GitHub?

**Comment by mauzey1** [comment]
@doutriaux1 Yes, I think they should be linking to the tables in https://github.com/PCMDI/cmip6-cmor-tables

**Comment by doutriaux1** [comment]
> There's is a duplicate of example 2 that is listed as example 3 in mydoc_cmor3_python.md.

Are you sure? It looks different on my computer.

**Comment by doutriaux1** [comment]
@mauzey1 ok i will update the links. Thx!

**Comment by mauzey1** [comment]
@doutriaux1 The duplicate entry is between line 267 and 457 on mydoc_cmor3_python.md

**Comment by doutriaux1** [comment]
@mauzey1 I fix the duplicate section, thx for catching this. I also figured out how to use the original markdown parser (`kramdown`) to process collapsed sections, added collapsed section to C and Fortran pages, I also fixed the tags that weren't showing up.

**Comment by doutriaux1** [comment]
@mauzey1 you might need to restart the jekyll server though in order for the collapsed section to be rendered properly

**Comment by mauzey1** [comment]
@doutriaux1 Should the tags link to pages that gather links with similar tags?  The "news" and "getting_started" tags do this but not the "examples" tag.  To get this functionality, you will need to make an HTML file for the tag similar to this https://github.com/PCMDI/cmor3_documentation/blob/master/tags/tag_news.html

**Comment by doutriaux1** [comment]
@mauzey1 I'm not sure what you want here, feel free to edit this PR please.

**Comment by mauzey1** [comment]
@doutriaux1 With tag_examples.html, you can now click on the "examples" tag on the Python example page and go to another page that gathers all links with that tag.  This might be a bit redundant with examples but could be applied to other tags to aggregate links from different parts of the site, such as news posts.  Do you want this done for the other tags?

**Pull request merged**
