### PR TITLE
CMOR 3.9.0 release

### PR DESCRIPTION
**Pull request by mauzey1**

### CODE REVIEW

**Comment by durack1** [comment]
Looks good @mauzey1.

I was hoping we could get the author list added to the pdf - where are the template files that define this? I wanted this to look similar to the past documentation manuals for CMOR1 [(here)](https://zenodo.org/records/12690071) and CMOR2 [(here)](https://zenodo.org/records/12690366)

**Comment by mauzey1** [comment]
@durack1  The template for the title page of the PDF is this: https://github.com/PCMDI/cmor3_documentation/blob/main/pdfconfigs/titlepage.html

I'll try putting the author names from CITATION.cff here.

**Comment by durack1** [comment]
> I'll try putting the author names from CITATION.cff here.

@mauzey1 if that is easy, that would be ideal

**Comment by mauzey1** [comment]
Authors will now be listed in the title page.
Screenshot 2024-08-28 at 14-13-12 CMOR 3 - mydoc pdf

**Comment by durack1** [comment]
> Authors will now be listed in the title page.

Good enough for me, thanks @mauzey1

**Review by durack1 — APPROVED** [review]

**Pull request merged**
